config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  get '/', to: 'users#index', as: 'home'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
    resources :likes, only: [:create]
      resources :comments, only: [:new, :create]
  end
end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, class_name: 'User'
  belongs_to :post, class_name: 'Post'
  has_many :likes, dependent: :destroy

  after_create :update_comment_count

  def update_comment_count
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  after_create :increment_likes_counter

  def increment_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: 'User'
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  before_create :increment_user_posts_counter

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def increment_user_posts_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :name, presence: true
  # validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  has_many :posts, foreign_key: 'author_id', dependent: :destroy, counter_cache: true
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  # validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }

  def most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    attributes = [:name]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = @user
    if @comment.save
      redirect_to user_post_path(@user, @post), notice: 'Comment created!'
    else
      flash.now[:errors] = 'Invalid comment!'
      render :new
    end
  end

  def destroy
    @commentdel = Comment.includes(:post).find(params[:id])
    @post = @commentdel.post

    if @commentdel.destroy
      flash[:notice] = 'Comment deleted!'
    else
      flash.now[:errors] = 'Unable to delete comment!'
    end
    redirect_to user_post_path(@post.author, @post)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/concerns/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
end

app/controllers/concerns/posts_controller.rb
class PostsController < ApplicationController
  def index; end

  def show
    @post = Post.includes(:author).find_by(author_id: params[:user_id], id: params[:id])

    if @post
      @user = @post.author
      @comments = @post.comments

    else
      flash[:alert] = 'Post not found'
      redirect_to user_posts_path(params[:user_id])
    end
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @user = current_user
    @post = @user.posts.new(post_params)
    if @post.save
      redirect_to user_post_path(@user, @post)
    else
      puts @user
      puts @post.errors.full_messages
      flash.now[:errors] = 'Invalid post!'
      render :new
    end
  end

  def destroy
    @post = Post.find_by(author_id: params[:user_id], id: params[:id])
    @post.destroy

    if @post.destroyed?
      flash[:notice] = 'Post deleted!'
      redirect_to user_posts_path(@post.author)
    else
      flash.now[:errors] = 'Unable to delete post!'
      redirect_to user_post_path(@post.author, @post)
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @user = current_user
    @like = Like.new(user_id: @user.id, post_id: @post.id)
    return unless @like.save

    redirect_to user_post_path(@user.id, @post)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
    if @user
      @recent_posts = @user.most_recent_posts
    else
      flash[:alert] = 'User not found'
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/comments/new.html.erb
<div class="comment-container">
<h3>Add a new Comment</h3>
<div class="comment-form">
<%= form_with model: [@user, @post, @comment], url: user_post_comments_path do |f| %>
<div>
<%= f.label :text, required: true%>
<%= f.text_field :text, required: true %>
</div>
<%= f.submit "Submit" %>
</div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     <% if flash[:notice].present? %>
      <div>
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert].present? %>
      <div>
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/likes/like.html.erb
<% stylesheet_link_tag('index')%>
<div class="likes-container">
<button class="Add-likes">Like comment/post</button>
<div class="comment-form">
</div>
</div>

app/views/posts/index.html.erb
<div class="posts-show">
<div class="post-show">
<div class="post-title-show">
<h1><%= @post.title %></h1>

<div class="post-interact">
<p>comments: <%= @post.comments_counter %></p>
<p>likes: <%= @post.likes_counter %></p>
</div>
</div>

<div>
<p><%= @post.text %></p>
</div>

</div>
<div class= "shared-comment-cont">
<div class="shared-comments">
<%= link_to "Add Comment", new_user_post_comment_path(@user, @post) %>
<%= form_with url: user_post_likes_path(@post.author.id, @post.id) do |form| %>
<%= form.submit 'Like' %>
<% end %>
</div>
<h2>Comments</h2>
<%= render "shared/comments", comments:@comments %>
</div>
</div>

app/views/posts/new.html.erb
<div class= "post-form">
  <h2 class= "create-post">Create a post</h2>

  <%= form_with model: @post, url: user_posts_path(@user) do |f| %>
    <div class= "title-input">
      <%= f.label :title %>
      <%= f.text_field :title, required: true %>
    </div>

    <div class= "comment-input">
      <%= f.label :text %>
      <%= f.text_field :text, required: true %>
    </div>

    <div class= "submit">
      <%= f.submit "Submit" %>
    </div>
  <% end %>

</div>

app/views/posts/show.html.erb
<div class="posts-show">
<div class="post-show">

<div class="post-title-show">
<h1><%= @post.title %></h1>

<div class="post-interact">
<p>comments: <%= @post.comments_counter %></p>
<p>likes: <%= @post.likes_counter %></p>
</div>
</div>

<div>
<p><%= @post.text %></p>
</div>

</div>
<div class= "shared-comment-cont">
<div class="shared-comments">
<%= link_to "Add Comment", new_user_post_comment_path(@user, @post) %>
<%= form_with url: user_post_likes_path(@post.author.id, @post.id) do |form| %>
<%= form.submit 'Like' %>
<% end %>
</div>
<h2>Comments</h2>
<%= render "shared/comments", comments:@comments %>
</div>

</div>

app/views/shared/_comments.html.erb
<div class="comments">
  <% comments.each do |comment| %>
    <div class="comment">
      <p><%= comment.user.name%> :<%= comment.text %></p>
    </div>
  <% end %>
</div>

app/views/shared/_post.html.erb
<div class="post">
<%=link_to user_post_path(user, post) do %>
<div class="single-post-cont">
<div class="post-title">
<h1><%= post.title %></h1>
</div>
<div class="post-content">
<p><%= post.text %></p>
</div>
<div class="interactions">
<p>comments: <%= post.comments_counter %></p>
<p>likes: <%= post.likes_counter %></p>
</div>
</div>
<% end %>
</div>

app/views/shared/_user.html.erb
<div class="user-container">
<%=link_to user_path(user) do %>
<div class="container-components">
<div class="img-container">
<img src="<%= user.photo_link %>"
alt="<%= user.name %>" />
</div>
<div class="userpost-container">
<h1 class="user-name"><%= user.name %></h1>
<p class="user-post">Number of posts: <%= user.posts_counter %></p>
</div>
</div>
<% end %>

</div>

app/views/users/index.html.erb
<div class="users">
<% @users.each do |user| %>
<%= render 'shared/user', user:user %>
<% end %>
<div class="users">
<% @users.each do |user| %>
<%= render 'shared/user', user:user %>
<% end %>
</div>

app/views/users/show.html.erb
<div class="show-page">
<div class="users">
<%= render 'shared/user', user:@user %>
</div>
<div>
    <%= @user.bio%>
</div>

<div class="posts">
<h2>Recent Posts</h2>
<% @recent_posts.each do |post| %>
<%= render 'shared/post', post:post, user:@user %>
<% end %>
</div>
<%=link_to 'See all posts', user_posts_path(@user) %>
</div>